sudo: true
language: android
dist: trusty
jdk: openjdk8
android:
  components:
    # Uncomment the lines below if you want to use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The Build Tools version used by your project
    - build-tools-30.0.1

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

addons:
  sonarcloud:
    organization: "adaway"
    token:
      secure: "ZRnnHEAPLuSaDxAMU+VEIENuIxtspqGWdeoyEGg/U3KdL5dTbUIyQ/gnZQTrtujpYkGm4Nubm06lZqmio+wSqvJour93rfU0fRTre3zAD8f/BcBVm/2D0ZNWOBd/rYMe/diNE1dTz1XTee0Pe9eJmnAt+bFQURzmqVodXs13u8SFvMKD7oXUwi57OrbXnGAnzk8ICP60DG0CEdmAEfss4aO91JTUFBec+UcG8aCs/F7TrP+Nxk7e1tSxnmNy8GJSoLvOudbIqW2R/wdz8bnY0DCUySe11c2OZPxSNkMy8F8S2kq5TdY5iaUY7h36+KLBwjoerX/Wp2XmjCst+ZZX/pmbOSG9/2TilvIP3M8iozMJjP3SHSQEq4Qd04WCrtKdDjLkl1CRVOCXFEmoEtDtOzowNGuKs3cz9bXvvesjSlJRqweqwvJKk8HAbP/yBwKrqxQWERDjohqMwhhh4hxfKRMCv0oiVaoiWongd/hnsbljq/QEcHfb76n2RTaxkMCq5SDrzGZmc7FxPzLl0OIh6+qffqZRWFmbaMmWD7STOXa7qBQ/xpfpTuuOh0LKclScEgDw4/4jbl/MLWdnpqXwuA7QHvx8opQJR7lYHEAiHp3elrMP7CR34wtTum6wysFMimiRnmti79RGR2EtP/0F3ZJgPYfRlOwwxd3DefeThOg="

install:
  - echo y | sdkmanager "ndk;21.3.6528147"

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./gradlew sonarqube; fi
