name: Android locale validation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'app/src/main/res/values*/string*.xml'

jobs:
  build:
    name: Validate locales
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47.0.1

      - name: Validate locale files
        id: validation
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          cd ${GITHUB_WORKSPACE}
          java .github/workflows/AndroidLocaleChecker.java ${ALL_CHANGED_FILES}

      - name: Commit patch
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        if: steps.validation.outputs.patch_applied == 'true'
        with:
          message: 'chore(locale): Fix contribution'
