name: Android locale validation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'app/src/main/res/values*/string*.xml'

jobs:
  build:
    name: Validate locales
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47

      - name: Validate locale files
        id: validation
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          cd ${GITHUB_WORKSPACE}
          java .github/workflows/AndroidLocaleChecker.java ${ALL_CHANGED_FILES}

      - name: Commit patch
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.validation.outputs.patch_applied == 'true'
        with:
          message: 'chore: Fix contribution'
