name: Android locale validation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'app/src/main/res/values*/string*.xml'

jobs:
  build:
    name: Validate locales
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.9 

      - name: Validate locale files
        id: validation
        run: |
          cd ${GITHUB_WORKSPACE}
          java .github/workflows/AndroidLocaleChecker.java ${{ steps.changed-files.outputs.all_modified_files }}

      - name: Commit patch
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.validation.outputs.patch_applied == 'true'
        with:
          message: 'chore: Fix contribution'
